import {
	Baby,
	BadgeDollarSign,
	BaggageClaim,
	Banknote,
	Bath,
	Bike,
	Bird,
	Bitcoin,
	BookOpen,
	BriefcaseBusiness,
	Building2,
	Bus,
	Calculator,
	Camera,
	Car,
	Cat,
	ChefHat,
	CircleDollarSign,
	CircleEllipsis,
	CirclePlay,
	ClipboardList,
	Coffee,
	CreditCard,
	Dog,
	Dumbbell,
	Fish,
	Flower2,
	Fuel,
	Gamepad2,
	Gift,
	GraduationCap,
	HeartPulse,
	Hotel,
	House,
	Landmark,
	Laptop,
	Music,
	Package,
	PawPrint,
	PiggyBank,
	Pill,
	Plane,
	QrCode,
	Rabbit,
	ReceiptText,
	Shirt,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Stethoscope,
	Syringe,
	Tags,
	Ticket,
	Trees,
	TrendingUp,
	Turtle,
	Tv,
	Umbrella,
	Utensils,
	WalletCards,
	Wrench,
} from "lucide-react";
import type { ComponentType } from "react";

import { cn } from "#/lib/utils.ts";
import { CatFace, CatPlay, CatSitting } from "./cat-icons.tsx";

export const categoryIcons: Record<
	string,
	ComponentType<{ className?: string }>
> = {
	Baby,
	BaggageClaim,
	BadgeDollarSign,
	Banknote,
	Bath,
	BriefcaseBusiness,
	Bitcoin,
	Bike,
	Bird,
	BookOpen,
	Building2,
	Bus,
	Calculator,
	Camera,
	Car,
	Cat,
	CatFace,
	CatPlay,
	CatSitting,
	ChefHat,
	CircleDollarSign,
	CircleEllipsis,
	CirclePlay,
	ClipboardList,
	Coffee,
	CreditCard,
	Dog,
	Dumbbell,
	Fish,
	Flower2,
	Fuel,
	Gamepad2,
	GraduationCap,
	Gift,
	HeartPulse,
	Hotel,
	House,
	Laptop,
	Landmark,
	Music,
	Package,
	PawPrint,
	Pill,
	PiggyBank,
	Plane,
	QrCode,
	Rabbit,
	ReceiptText,
	Shirt,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Stethoscope,
	Syringe,
	Tags,
	Ticket,
	TrendingUp,
	Trees,
	Turtle,
	Tv,
	Utensils,
	Umbrella,
	WalletCards,
	Wrench,
};

const colorClasses: Record<string, string> = {
	amber: "bg-amber-400",
	blue: "bg-blue-500",
	cyan: "bg-cyan-500",
	emerald: "bg-emerald-500",
	indigo: "bg-indigo-500",
	lime: "bg-lime-500",
	orange: "bg-orange-500",
	pink: "bg-pink-500",
	red: "bg-red-500",
	rose: "bg-rose-500",
	sky: "bg-sky-500",
	slate: "bg-slate-500",
	teal: "bg-teal-500",
	violet: "bg-violet-500",
	fuchsia: "bg-fuchsia-500",
};

const iconColorClasses: Record<string, string> = {
	amber: "text-amber-500",
	blue: "text-blue-500",
	cyan: "text-cyan-500",
	emerald: "text-emerald-500",
	indigo: "text-indigo-500",
	lime: "text-lime-500",
	orange: "text-orange-500",
	pink: "text-pink-500",
	red: "text-red-500",
	rose: "text-rose-500",
	sky: "text-sky-500",
	slate: "text-slate-500",
	teal: "text-teal-500",
	violet: "text-violet-500",
	fuchsia: "text-fuchsia-500",
};

export function CategoryMark({
	colorKey,
	iconKey,
	className,
	iconClassName,
	variant = "badge",
}: {
	colorKey: string;
	iconKey: string;
	className?: string;
	iconClassName?: string;
	variant?: "badge" | "icon";
}) {
	const Icon = categoryIcons[iconKey] ?? Tags;

	return (
		<span
			className={cn(
				"inline-flex size-9 shrink-0 items-center justify-center",
				variant === "badge"
					? ["rounded-xl text-white", colorClasses[colorKey] ?? "bg-slate-500"]
					: (iconColorClasses[colorKey] ?? "text-slate-500"),
				className,
			)}
		>
			<Icon className={cn("size-4", iconClassName)} />
		</span>
	);
}
